### ISSUE TITLE
Console log state setting not honored

### ISSUE THREAD

**Issue by rmtheis** [Instabug/android-sample#14]
Once a minute, Instabug is spamming the device log with a stack trace. This happens when I'm using Charles to proxy device traffic.

I am using `.setConsoleLogState(Feature.State.DISABLED)` but I still see these messages.

    12-19 09:58:02.818 9118-9245/com.xxxxxxxxxxxxxxxxxxxxxxxxxx E/INSTABUG -: Network request got error
    12-19 09:58:02.819 9118-9245/com.xxxxxxxxxxxxxxxxxxxxxxxxxx E/INSTABUG - c: Error getting Network request response: {"status":"You are not allowed to message this issue"}
    12-19 09:58:02.821 9118-9245/com.xxxxxxxxxxxxxxxxxxxxxxxxxx E/INSTABUG -: Request got error: https://api.instabug.com/api/sdk/v3/chats/sync
                                                                              com.instabug.library.network.d: No network connection - responseCode: 406
                                                                              
                                                                                  at com.instabug.library.network.c.d(NetworkManager.java:237)
                                                                                  at com.instabug.library.network.c.a(NetworkManager.java:32)
                                                                                  at com.instabug.library.network.c$1.a(NetworkManager.java:83)
                                                                                  at com.instabug.library.network.c$1.call(NetworkManager.java:59)
                                                                                  at rx.Observable.unsafeSubscribe(Observable.java:10150)
                                                                                  at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                                  at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
                                                                                  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                                  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                  at java.lang.Thread.run(Thread.java:818)

**Comment by rmtheis** [comment]
Possibly related: #3

**Comment by DevHossamHassan** [comment]
Hey @rmtheis 
Thanks for reporting this issue 
We're currently fixing it, and we will notify you when we finish.
By the way,
.setConsoleLogState(Feature.State.DISABLED) 
is used for Enabling/disabling console log to be added to reports.
not for Enabling/disabling Instabug logging with the stack trace.
you can use 
```java
 Instabug.setDebugEnabled(false);
```
for that purpose.
Please let me know if there's anything more I can help you with.

**Comment by DevHossamHassan** [comment]
Hey @ramidoss
We shipped a fix for this issue in v4.0.2 please check it out.
Thank you so much for your patience.

**Comment by rmtheis** [comment]
Thanks for the fix! It looks to me like it's working.

Closing this issue...
