### ISSUE TITLE
ConcurrentModificationException in Instabug.Builder

### ISSUE THREAD

**Issue by sfseyhan** [Instabug/android-sample#141]
We got the following crash report in production, so far only 1 occurrence. No reproduction steps.

### Stacktrace:
Caused by java.util.ConcurrentModificationException
       at java.util.Hashtable$Enumerator.next(Hashtable.java:1187)
       at org.jacoco.agent.rt.internal_8ff85ea.ConfigLoader.loadSystemProperties(ConfigLoader.java:56)
       at org.jacoco.agent.rt.internal_8ff85ea.ConfigLoader.load(ConfigLoader.java:37)
       at org.jacoco.agent.rt.internal_8ff85ea.Offline.(Offline.java:29)
       at com.instabug.library.Instabug$Builder.$jacocoInit(Instabug.java)
       at com.instabug.library.Instabug$Builder.(Instabug.java)
       at com.takeaway.driver.DriverApplication.onCreate(DriverApplication.java:130)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1046)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5586)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1625)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6339)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

### Instabug integration code
```
public class DriverApplication extends Application {
@Override
    public void onCreate() {
        super.onCreate();
        new Instabug.Builder(this, BuildConfig.INSTABUG_TOKEN)
                .setInvocationEvents(InstabugInvocationEvent.NONE)
                .build();
}
}
```

### SDK Version
8.0.11

### Android Version
7.1.1

### Device Model
Moto E (4) Plus

**Comment by Korazy** [comment]
Hey @sfseyhan 

Thanks for reaching out. We created a quick fix for you in this snapshot, can you give it a go? 8.0.11.5-SNAPSHOT

To grab the snapshot add the following to your code:
repositories {
    maven {
        // TODO add this only if interested in getting SNAPSHOT releases
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}

**Comment by sfseyhan** [comment]
@Korazy thanks for the quick fix but I can't reproduce it myself, it's a crash report we got from a user. So I cannot confirm if this new build fixes the issue or not.
