### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by papfonseca** [Instabug/android-sample#15]
Hi,

I´m getting this exception: ConcurrentModificationException.

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.instabug.library.InstabugFeedbackActivity}: java.util.ConcurrentModificationException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.access$1100(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.util.ConcurrentModificationException
       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
       at org.json.JSONArray.writeTo(JSONArray.java:612)
       at org.json.JSONArray.toString(JSONArray.java:585)
       at com.instabug.library.logging.InstabugLog.getLogMessages(InstabugLog.java:184)
       at com.instabug.library.logging.InstabugLog.getLogs(InstabugLog.java:172)
       at com.instabug.library.model.l$a.E(State.java:964)
       at com.instabug.library.model.l$a.a(State.java:675)
       at com.instabug.library.model.Bug$b.a(Bug.java:248)
       at com.instabug.library.o.a(LiveBugManager.java:45)
       at com.instabug.library.InstabugFeedbackActivity.onCreate(InstabugFeedbackActivity.java:110)
       at android.app.Activity.performCreate(Activity.java:6876)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.access$1100(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Any idea? I'm using the latest sdk version.

**Comment by vezikon** [comment]
Hello @papfonseca, This issue is fixed in v4.0.6
Please, consider upgrading to this version.
