### ISSUE TITLE
Getting exception while launching from AcionBar button

### ISSUE THREAD

**Issue by gnani185** [Instabug/android-sample#18]
Launch Code:
Instabug.invoke(InstabugInvocationMode.NEW_BUG);

Exception:

02-09 23:49:48.418 974-974/com.devsparkles.lyrics E/INSTABUG - a: capture view hierarchy image got error: width and height must be > 0, time in MS: 1486664388417
                                                                  java.lang.IllegalArgumentException: width and height must be > 0
                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:855)
                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:834)
                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:765)
                                                                      at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:641)
                                                                      at com.instabug.library.h.a.a.a.a(BitmapUtils.java:110)
                                                                      at com.instabug.library.h.a.a.a.d(BitmapUtils.java:77)
                                                                      at com.instabug.library.h.a.a.a.c(BitmapUtils.java:34)
                                                                      at com.instabug.library.h.a.a.a.b(BitmapUtils.java:19)
                                                                      at com.instabug.library.h.a.a.a$1.a(BitmapUtils.java:25)
                                                                      at com.instabug.library.h.a.a.a$1.call(BitmapUtils.java:22)
                                                                      at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
                                                                      at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
                                                                      at rx.Observable.unsafeSubscribe(Observable.java:10150)
                                                                      at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                      at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                      at android.os.Handler.handleCallback(Handler.java:746)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
02-09 23:49:48.419 974-974/com.devsparkles.lyrics E/INSTABUG - a: inspect current activity got errorwidth and height must be > 0, time in MS: 1486664388418
                                                                  java.lang.IllegalArgumentException: width and height must be > 0
                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:855)
                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:834)
                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:765)
                                                                      at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:641)
                                                                      at com.instabug.library.h.a.a.a.a(BitmapUtils.java:110)
                                                                      at com.instabug.library.h.a.a.a.d(BitmapUtils.java:77)
                                                                      at com.instabug.library.h.a.a.a.c(BitmapUtils.java:34)
                                                                      at com.instabug.library.h.a.a.a.b(BitmapUtils.java:19)
                                                                      at com.instabug.library.h.a.a.a$1.a(BitmapUtils.java:25)
                                                                      at com.instabug.library.h.a.a.a$1.call(BitmapUtils.java:22)
                                                                      at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
                                                                      at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
                                                                      at rx.Observable.unsafeSubscribe(Observable.java:10150)
                                                                      at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                      at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                      at android.os.Handler.handleCallback(Handler.java:746)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by tarek360** [comment]
Hi,
Sorry for that exception, is that exception happen with you every time and on different devices?

**Comment by gnani185** [comment]
I'm tesing with one device Moto G3. Not sure about other devices. Just now started integrating it.

**Comment by lukasz-gosiewski** [comment]
@tarek360 Got the same problem on all devices. I'm using instabug for a while now and this is the first time it occured. Are there any quick fixes to apply or I need to wait for you to repair it ?

**Comment by lukasz-gosiewski** [comment]
Moreover it occurs all the time, no matter which method of invocation i choose.

**Comment by lukasz-gosiewski** [comment]
Fallback to 3.4.0 version do the trick.

**Comment by tarek360** [comment]
Hi @gnani185 and @lukasz-gosiewski
We have fixed this issue, please update to v4.0.2
Thank you.
