### ISSUE TITLE
Getting IllegalArgumentException when invoking Instabug.invoke(InstabugInvocationMode.NEW_FEEDBACK)

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#20]
There is a **Feedback** entry in our settings fragment. Click event handling is to invoke `Instabug.invoke(InstabugInvocationMode.NEW_FEEDBACK)` programmatically. But I get `java.lang.IllegalArgumentException: width and height must be > 0` and nothing shows up except a loading dialog. The following are logs:

```
capture view hierarchy image got error: width and height must be > 0, time in MS: 1487049486032
                                                                       java.lang.IllegalArgumentException: width and height must be > 0
                                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:877)
                                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
                                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
                                                                           at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:663)
                                                                           at com.instabug.library.h.a.a.a.a(BitmapUtils.java:110)
                                                                           at com.instabug.library.h.a.a.a.d(BitmapUtils.java:77)
                                                                           at com.instabug.library.h.a.a.a.c(BitmapUtils.java:37)
                                                                           at com.instabug.library.h.a.a.a.b(BitmapUtils.java:19)
                                                                           at com.instabug.library.h.a.a.a$1.a(BitmapUtils.java:25)
                                                                           at com.instabug.library.h.a.a.a$1.call(BitmapUtils.java:22)
                                                                           at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:47)
                                                                           at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:36)
                                                                           at rx.Observable.unsafeSubscribe(Observable.java:8666)
                                                                           at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                           at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

So why is this happening? What's strange is that it works when I invoke the same `Instabug.invoke(InstabugInvocationMode.NEW_FEEDBACK)` somewhere else in the App. And also, I don't want any attachment when users use Instabug from this entry but other entries opposite. What is the proper way to achieve that? The following are the initialization code in `Application`:
```
new Instabug.Builder((Application) pContext.getApplicationContext(), BuildConfig.INSTABUG_KEY)
				.setEmailFieldRequired(false)
				.setCommentFieldRequired(false)
				.setInvocationEvent(InstabugInvocationEvent.NONE)
				.setIntroMessageEnabled(false)
				.setCrashReportingState(Feature.State.DISABLED)
				.setTrackingUserStepsState(Feature.State.DISABLED)
				.setAttachmentTypesEnabled(true, true, true, true, true)
				.build();

		if (AccountManager.getInstance().hasAccount()) {
			Instabug.setUserData(AccountManager.getInstance().getCurrentAccount().getUid());
		}
		Instabug.setDebugEnabled(BuildConfig.DEBUG);
```

I have another question related to this:
What are the essential differences between `NEW_BUG` and `NEW_FEEDBACK` when I invoke `Instabug.invoke()`?

**Comment by saiday** [comment]
Same issue here.

Additional:
even `.setWillSkipScreenshotAnnotation(true)` set, Instabug is trying to take screenshot.

**Comment by vezikon** [comment]
Hello, 

Can you give it a try on v4.0.2?

**Comment by gejiaheng** [comment]
@vezikon 
v4.0.2 works fine.

**Comment by saiday** [comment]
@vezikon `4.0.2` works, thanks!
