### ISSUE TITLE
Nullpointer Exception

### ISSUE THREAD

**Issue by csaba-csete-87** [Instabug/android-sample#25]
Hi guys!
The following exception showed up in one of our crash reports:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
	at com.instabug.library.model.e.a(ConsoleLog.java:44)
	at com.instabug.library.model.j.y(State.java:336)
	at com.instabug.library.model.j.J(State.java:500)
	at com.instabug.library.model.j.a(State.java:521)
	at com.instabug.library.messaging.b.a.a(Chat.java:244)
	at com.instabug.library.internal.c.a.j.a(OnDiskCache.java:163)
	at com.instabug.library.internal.c.a.j.a(OnDiskCache.java:24)
	at com.instabug.library.internal.c.a.f.a(CacheManager.java:208)
	at com.instabug.library.internal.c.a.f.a(CacheManager.java:182)
	at com.instabug.library.messaging.a.a.b(ChatsCacheManager.java:65)
	at com.instabug.library.p$2.run(SessionManager.java:182)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by MoustafaMesbah** [comment]
Hey @csaba-csete-87
we will release a fix for this crash ASAP, can you tell me us which version of SDK you are using?

**Comment by csaba-csete-87** [comment]
Hi @MoustafaMesbah 
we are using the version 4.0.1

**Comment by DevHossamHassan** [comment]
Hello @csaba-csete-87,
I believe this issue has been fixed.
Is it still exists?
if it is, please don't hesitate to inform us.
