### ISSUE TITLE
capture view hierarchy image got error: width and height must be > 0

### ISSUE THREAD

**Issue by willybrodus** [Instabug/android-sample#26]
03-13 14:48:57.771 14703-14703/com.medicall.patient E/INSTABUG - a: capture view hierarchy image got error: width and height must be > 0, time in MS: 1489391337788
                                                                    java.lang.IllegalArgumentException: width and height must be > 0
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:817)
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:796)
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:728)
                                                                        at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:604)
                                                                        at com.instabug.library.h.a.a.a.a(BitmapUtils.java:110)
                                                                        at com.instabug.library.h.a.a.a.d(BitmapUtils.java:77)
                                                                        at com.instabug.library.h.a.a.a.c(BitmapUtils.java:34)
                                                                        at com.instabug.library.h.a.a.a.b(BitmapUtils.java:19)
                                                                        at com.instabug.library.h.a.a.a$1.a(BitmapUtils.java:25)
                                                                        at com.instabug.library.h.a.a.a$1.call(BitmapUtils.java:22)
                                                                        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
                                                                        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
                                                                        at rx.Observable.unsafeSubscribe(Observable.java:10150)
                                                                        at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                        at android.os.Handler.handleCallback(Handler.java:733)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5111)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                        at dalvik.system.NativeStart.main(Native Method)
03-13 14:48:57.781 14703-14703/com.medicall.patient E/INSTABUG - a: inspect current activity got errorwidth and height must be > 0, time in MS: 1489391337789
                                                                    java.lang.IllegalArgumentException: width and height must be > 0
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:817)
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:796)
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:728)
                                                                        at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:604)
                                                                        at com.instabug.library.h.a.a.a.a(BitmapUtils.java:110)
                                                                        at com.instabug.library.h.a.a.a.d(BitmapUtils.java:77)
                                                                        at com.instabug.library.h.a.a.a.c(BitmapUtils.java:34)
                                                                        at com.instabug.library.h.a.a.a.b(BitmapUtils.java:19)
                                                                        at com.instabug.library.h.a.a.a$1.a(BitmapUtils.java:25)
                                                                        at com.instabug.library.h.a.a.a$1.call(BitmapUtils.java:22)
                                                                        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
                                                                        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
                                                                        at rx.Observable.unsafeSubscribe(Observable.java:10150)
                                                                        at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                        at android.os.Handler.handleCallback(Handler.java:733)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5111)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                        at dalvik.system.NativeStart.main(Native Method)
03-13 14:48:57.781 14703-14703/com.medicall.patient E/INSTABUG - a: prepare screenshots for invocation got error: width and height must be > 0, time in MS: 1489391337790
                                                                    java.lang.IllegalArgumentException: width and height must be > 0
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:817)
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:796)
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:728)
                                                                        at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:604)
                                                                        at com.instabug.library.h.a.a.a.a(BitmapUtils.java:110)
                                                                        at com.instabug.library.h.a.a.a.d(BitmapUtils.java:77)
                                                                        at com.instabug.library.h.a.a.a.c(BitmapUtils.java:34)
                                                                        at com.instabug.library.h.a.a.a.b(BitmapUtils.java:19)
                                                                        at com.instabug.library.h.a.a.a$1.a(BitmapUtils.java:25)
                                                                        at com.instabug.library.h.a.a.a$1.call(BitmapUtils.java:22)
                                                                        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
                                                                        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
                                                                        at rx.Observable.unsafeSubscribe(Observable.java:10150)
                                                                        at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                        at android.os.Handler.handleCallback(Handler.java:733)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5111)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                        at dalvik.system.NativeStart.main(Native Method)

I have some problem with that eror. Please help me. Thank you.

**Comment by tarek360** [comment]
Hi @willybrodus , Please tell me what's the version which you use?

**Comment by willybrodus** [comment]
Hi, I use instabug version 4.0.1 but now I using instabug version 4.0.2 and
my problem is solved. Thank you for attention and thank you for develop
Instabug :)


Regards from Indonesia,

Willy

2017-03-13 16:18 GMT+07:00 Ahmed Tarek <notifications@github.com>:

**Comment by tarek360** [comment]
Thank you @willybrodus :)
