### ISSUE TITLE
More messages in device log

### ISSUE THREAD

**Issue by rmtheis** [Instabug/android-sample#27]
Multiple times per second, Instabug is spamming the device log with a stack trace. This happens when I'm using Charles to proxy device traffic.

Possibly related: #14 

Using Instabug version 4.0.2

    E/INSTABUG -: Request got error: https://api.instabug.com/api/sdk/v3/crashes
    com.instabug.library.network.d: No network connection - responseCode: 503
    
    at com.instabug.library.network.c.d(NetworkManager.java:245)
    at com.instabug.library.network.c.a(NetworkManager.java:32)
    at com.instabug.library.network.c$1.a(NetworkManager.java:83)
    at com.instabug.library.network.c$1.call(NetworkManager.java:59)
    at rx.Observable.subscribe(Observable.java:10246)
    at rx.Observable.subscribe(Observable.java:10213)
    at com.instabug.library.crashreporting.network.a.a(CrashesService.java:85)
    at com.instabug.library.crashreporting.network.InstabugCrashesUploaderService.c(InstabugCrashesUploaderService.java:33)
    at com.instabug.library.crashreporting.network.InstabugCrashesUploaderService.a(InstabugCrashesUploaderService.java:24)
    at com.instabug.library.network.a.onHandleIntent(InstabugBackgroundService.java:31)
    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.os.HandlerThread.run(HandlerThread.java:61)
    
    E/INSTABUG -: Network request got error

**Comment by DevHossamHassan** [comment]
Hello @rmtheis,
I believe this issue has been fixed.
Is it still exists?  
if it is, please don't hesitate to inform us.
