### ISSUE TITLE
Instabug getting crashed after initialize in android

### ISSUE THREAD

**Issue by Karthikg206** [Instabug/android-sample#29]
I am using instabug 4.0.7.app getting crash after initialize.

crash log:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Dialog.setCanceledOnTouchOutside(boolean)' on a null object reference
       at com.instabug.library.g.f(InstabugDelegate.java:327)
       at com.instabug.library.g$5.run(InstabugDelegate.java:307)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

anyone know the issue?

**Comment by DevHossamHassan** [comment]
Hello @Karthikg206,
Thank you for reporting this issue, we are currently working on fixing it.
It would be great if you could help us reproduce your issue by sending us an android sample app contains the issue with minimum code lines possible.

**Comment by DevHossamHassan** [comment]
Hey @Karthikg206,
I have looked into it and I'm shipping a fix for this right now.
So you can avoid that crash by using `.setIntroMessageEnabled(false)` 
until we release that fix and it will take a couple of hours. 
Thank you again.

**Comment by Karthikg206** [comment]
ok suppose i want intro message means what to do

**Comment by DevHossamHassan** [comment]
Intro message works only with `SHAKE` and `TWO_FINGER_SWIPE_LEFT` invocation events.

**Comment by Karthikg206** [comment]
ok thank you

**Comment by DevHossamHassan** [comment]
I'm glad to help you @Karthikg206, 
please don't hesitate to reach us anytime.
regards.
