### ISSUE TITLE
Instabug Network errors

### ISSUE THREAD

**Issue by jbarmanet** [Instabug/android-sample#3]
Hi,

I migrated from Instabug 1.7 to instabug 2+

When I report a bug all goes well, and the issue is reported to the Instabug dashboard, but after that, it keeps throwing errors into my console every minute : 

`03-04 15:59:17.668 17336-17336/get.dop I/INSTABUG - e: syncMessages
03-04 15:59:17.934 17336-17384/get.dop E/INSTABUG - a: Error getting Network request response: {"status":"You are not allowed to email this issue"}
03-04 15:59:17.941 17336-17384/get.dop E/INSTABUG -: syncMessages request got error: 
                                                     com.instabug.library.network.b: No network connection - 406
                                                         at com.instabug.library.network.a.d(NetworkManager.java:239)
                                                         at com.instabug.library.network.a.a(NetworkManager.java:33)
                                                         at com.instabug.library.network.a$1.a(NetworkManager.java:83)
                                                         at com.instabug.library.network.a$1.call(NetworkManager.java:60)
                                                         at rx.Observable.unsafeSubscribe(Observable.java:7713)
                                                         at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
                                                         at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                         at java.lang.Thread.run(Thread.java:818)
03-04 15:59:17.942 17336-17384/get.dop E/INSTABUG -: Something went wrong while sync messages`

Any clue what's going on there ?

**Comment by mSobhy90** [comment]
Hi @jbarmanet, 
Sorry for the late reply, this issue is related to your plan not having in-app messaging feature available. They shouldn't appear anymore after a day of first seeing this.
Don't worry about it, it's not a crashing exception. It's just there to allow you to understand more about what's going on under-the-hood, but soon we'll be releasing a way to disable all Instabug logs.
Does that make any sense? Please let me know if there's anything more I can help you with, or if I wasn't clear in my answer.

**Comment by jbarmanet** [comment]
Hi, okay I understand, this makes sense. Thank your for this explanation... 
Looking forward to remove those error lines as it pollutes a little bit those useful logs ;-)

**Comment by ripern** [comment]
@jbarmanet Did those error lines ever disappear for you? I still have them in instabug 3+ and can't find any other information about it except this very issue.

Like you say it's very annoying to always see this in the log when starting my app.
