### ISSUE TITLE
Instabug crashes after choosing an attachment from gallery

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#32]
Console log:

```
Process: com.zhihu.android, PID: 32601
                                                                   java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=69398, result=-1, data=Intent { dat=file:///storage/emulated/0/DCIM/Camera/IMG_20170507_194215.jpg typ=image/jpeg }} to activity {com.zhihu.android/com.instabug.library.InstabugFeedbackActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getColumnIndexOrThrow(java.lang.String)' on a null object reference
                                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:3706)
                                                                       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3749)
                                                                       at android.app.ActivityThread.access$1400(ActivityThread.java:153)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getColumnIndexOrThrow(java.lang.String)' on a null object reference
                                                                       at com.instabug.library.internal.c.a.a(AttachmentManager.java:112)
                                                                       at com.instabug.library.bugreporting.a.c.a(FeedbackPresenter.java:198)
                                                                       at com.instabug.library.bugreporting.a.b.onActivityResult(FeedbackFragment.java:335)
                                                                       at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
                                                                       at android.app.Activity.dispatchActivityResult(Activity.java:6448)
                                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:3702)
                                                                       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3749) 
                                                                       at android.app.ActivityThread.access$1400(ActivityThread.java:153) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5441) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```
Phone: Xiaomi 5C
Model number: MI 5C
Android version: 6.0MRA58K
MIUI version: MIUI 8.1|Stable 8.1.14.0(MCJCNDI)
Instabug SDK version: 4.0.7

**Comment by DevHossamHassan** [comment]
Hello @gejiaheng, 
Thank you for reporting this issue and all provided details.
Because you are helping us improve our product, thank you so much 👍 
By the way, This issue has been fixed and it will be released in a couple of hours. 
Cheers :)

**Comment by DevHossamHassan** [comment]
Hey @gejiaheng, 
This issue should be fixed in the latest release which is version `4.0.10`
Please try it out when you have time and let us know if there is anything else we can help you with.
Regards

**Comment by gejiaheng** [comment]
@DevHossamHassan   
Thanks for your response. It is resolved.
