### ISSUE TITLE
Instabug causing app to crash on location.reload()

### ISSUE THREAD

**Issue by alexplummer** [Instabug/android-sample#37]
App is continuously crashing on location.reload(), here is the log:

java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2720)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2781)
  at android.app.ActivityThread.-wrap12(ActivityThread.java:0)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:241)
  at android.app.ActivityThread.main(ActivityThread.java:6274)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.NullPointerException: 
  at com.instabug.library.messaging.b.a.e(SynchronizationManager.java:100)
  at com.instabug.library.messaging.b.a.d(SynchronizationManager.java:120)
  at com.instabug.library.f.x(InstabugDelegate.java:335)
  at com.instabug.library.f.g(InstabugDelegate.java:303)
  at com.instabug.library.Instabug.disable(Instabug.java:761)
  at com.instabug.library.Instabug$Builder.build(Instabug.java:2343)
  at com.instabug.cordova.plugin.IBGPluginActivity.onCreate(IBGPluginActivity.java:53)
  at android.app.Activity.performCreate(Activity.java:6720)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2673)

**Comment by tarek360** [comment]
Thank you for reporting this crash, it is fixed, please update to the latest version 4.2.0
