### ISSUE TITLE
NullPointerException when trying to report a bug twice in a row

### ISSUE THREAD

**Issue by gzhu** [Instabug/android-sample#38]
I was trying it on 4.1.1

`java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList com.instabug.library.bugreporting.model.Bug.e()' on a null object reference
                                                                                  at com.instabug.library.bugreporting.a.d.c(FeedbackPresenter.java:233)
                                                                                  at com.instabug.library.bugreporting.a.c$6.onReceive(FeedbackFragment.java:695)
                                                                                  at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
                                                                                  at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
                                                                                  at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by tarek360** [comment]
@gzhu Thank you for reporting this crash, we are working on it and it will be fixed in the release.

**Comment by tarek360** [comment]
@gzhu fixed, please update to v4.2.0
