### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by AshotKarapetyan1** [Instabug/android-sample#39]
java.lang.RuntimeException: Unable to start activity ComponentInfo{.DebugLogsActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2118)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2145)
	at android.app.ActivityThread.access$600(ActivityThread.java:130)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4847)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:535)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at android.content.ComponentName.<init>(ComponentName.java:75)
	at android.content.Intent.<init>(Intent.java:3305)
	at com.instabug.library.t.a(SessionManager.java:116)
	at com.instabug.library.t.e(SessionManager.java:64)
	at com.instabug.library.t.a(SessionManager.java:41)
	at com.instabug.library.i.a(InstabugDelegate.java:510)
	at com.instabug.library.Instabug.notifyDelegateActivityStarted(Instabug.java:122)
	at com.instabug.library.d.onActivityStarted(InstabugActivityLifecycleListener.java:21)
	at android.app.Application.dispatchActivityStarted(Application.java:164)
	at android.app.Activity.onStart(Activity.java:1056)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:589)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1188)
	at android.app.Activity.performStart(Activity.java:5197)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2073)
	... 11 more

Caused by: 
java.lang.NullPointerException
	at android.content.ComponentName.<init>(ComponentName.java:75)
	at android.content.Intent.<init>(Intent.java:3305)
	at com.instabug.library.t.a(SessionManager.java:116)
	at com.instabug.library.t.e(SessionManager.java:64)
	at com.instabug.library.t.a(SessionManager.java:41)
	at com.instabug.library.i.a(InstabugDelegate.java:510)
	at com.instabug.library.Instabug.notifyDelegateActivityStarted(Instabug.java:122)
	at com.instabug.library.d.onActivityStarted(InstabugActivityLifecycleListener.java:21)
	at android.app.Application.dispatchActivityStarted(Application.java:164)
	at android.app.Activity.onStart(Activity.java:1056)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:589)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1188)
	at android.app.Activity.performStart(Activity.java:5197)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2073)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2145)
	at android.app.ActivityThread.access$600(ActivityThread.java:130)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4847)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:535)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by tarek360** [comment]
Hi @AshotKarapetyan1 
Thank you for reporting this, please let me know the Instabug SDK version.

**Comment by AshotKarapetyan1** [comment]
The exception has occurred in version 2.5.0

**Comment by tarek360** [comment]
Hi @AshotKarapetyan1 as I told you [here](https://github.com/Instabug/android-sample/issues/40#issuecomment-308677841) please update to Insatbug version 4.1.1 and let me know if you have another issue.
Thank you.
