### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by AshotKarapetyan1** [Instabug/android-sample#40]
java.lang.RuntimeException: Unable to stop activity .MenuActivity}: java.lang.StringIndexOutOfBoundsException: length=116302; regionStart=0; regionLength=-1
	at android.app.ActivityThread.handleSleeping(ActivityThread.java:3372)
	at android.app.ActivityThread.access$2900(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1389)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5097)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.StringIndexOutOfBoundsException: length=116302; regionStart=0; regionLength=-1
	at java.lang.String.startEndAndLength(String.java:588)
	at java.lang.String.substring(String.java:1475)
	at com.instabug.library.internal.d.a.i.e(OnDiskCache.java:232)
	at com.instabug.library.internal.d.a.i.a(OnDiskCache.java:96)
	at com.instabug.library.internal.d.a.i.a(OnDiskCache.java:118)
	at com.instabug.library.internal.d.a.i.a(OnDiskCache.java:28)
	at com.instabug.library.internal.d.a.e.a(CacheManager.java:200)
	at com.instabug.library.internal.d.a.h.b(IssuesCacheManger.java:49)
	at com.instabug.library.t.d(SessionManager.java:83)
	at com.instabug.library.t.b(SessionManager.java:68)
	at com.instabug.library.i.d(InstabugDelegate.java:569)
	at com.instabug.library.Instabug.notifyDelegateActivityStopped(Instabug.java:155)
	at com.instabug.library.d.onActivityStopped(InstabugActivityLifecycleListener.java:41)
	at android.app.Application.dispatchActivityStopped(Application.java:226)
	at android.app.Activity.onStop(Activity.java:1397)
	at android.support.v4.app.FragmentActivity.onStop(FragmentActivity.java:619)
	at android.support.v7.app.AppCompatActivity.onStop(AppCompatActivity.java:184)
	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1235)
	at android.app.Activity.performStop(Activity.java:5393)
	at android.app.ActivityThread.handleSleeping(ActivityThread.java:3369)
	... 10 more

Caused by: 
java.lang.StringIndexOutOfBoundsException: length=116302; regionStart=0; regionLength=-1
	at java.lang.String.startEndAndLength(String.java:588)
	at java.lang.String.substring(String.java:1475)
	at com.instabug.library.internal.d.a.i.e(OnDiskCache.java:232)
	at com.instabug.library.internal.d.a.i.a(OnDiskCache.java:96)
	at com.instabug.library.internal.d.a.i.a(OnDiskCache.java:118)
	at com.instabug.library.internal.d.a.i.a(OnDiskCache.java:28)
	at com.instabug.library.internal.d.a.e.a(CacheManager.java:200)
	at com.instabug.library.internal.d.a.h.b(IssuesCacheManger.java:49)
	at com.instabug.library.t.d(SessionManager.java:83)
	at com.instabug.library.t.b(SessionManager.java:68)
	at com.instabug.library.i.d(InstabugDelegate.java:569)
	at com.instabug.library.Instabug.notifyDelegateActivityStopped(Instabug.java:155)
	at com.instabug.library.d.onActivityStopped(InstabugActivityLifecycleListener.java:41)
	at android.app.Application.dispatchActivityStopped(Application.java:226)
	at android.app.Activity.onStop(Activity.java:1397)
	at android.support.v4.app.FragmentActivity.onStop(FragmentActivity.java:619)
	at android.support.v7.app.AppCompatActivity.onStop(AppCompatActivity.java:184)
	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1235)
	at android.app.Activity.performStop(Activity.java:5393)
	at android.app.ActivityThread.handleSleeping(ActivityThread.java:3369)
	at android.app.ActivityThread.access$2900(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1389)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5097)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by tarek360** [comment]
Hi @AshotKarapetyan1
Thank you for reporting this, please let me know the Instabug SDK version.

**Comment by AshotKarapetyan1** [comment]
The exception has occurred in version 2.6.2

**Comment by tarek360** [comment]
@AshotKarapetyan1 This is an old version, the latest version is 4.1.1, we have fixed a lot of issues and released a lot of new features too, please update to Insatbug version 4.1.1 and let me know if you have another issue.
Thank you.

**Comment by tarek360** [comment]
Hi @AshotKarapetyan1 as I told you [here](https://github.com/Instabug/android-sample/issues/40#issuecomment-308677841) please update to Insatbug version 4.1.1 and let me know if you have another issue.
Thank you.
