### ISSUE TITLE
NoSuchFieldException in InstabugFeedbackActivity

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#44]
We have a crash in our gated launch:

crash log: 

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zhihu.android/com.instabug.library.InstabugFeedbackActivity}: com.instabug.library.d.a.c: java.lang.NoSuchFieldException: No field mView in class Landroid/view/ColorViewRootImpl; (declaration of 'android.view.ColorViewRootImpl' appears in /system/framework/framework.jar:classes2.dex)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2687)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2753)
       at android.app.ActivityThread.access$1100(ActivityThread.java:186)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1609)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:238)
       at android.app.ActivityThread.main(ActivityThread.java:6016)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:937)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:798)
Caused by com.instabug.library.d.a.c: java.lang.NoSuchFieldException: No field mView in class Landroid/view/ColorViewRootImpl; (declaration of 'android.view.ColorViewRootImpl' appears in /system/framework/framework.jar:classes2.dex)
       at com.instabug.library.d.c.a.a(FieldHelper.java:87)
       at com.instabug.library.d.c.a.a(FieldHelper.java:54)
       at com.instabug.library.f.a.a.a(ActivityViewInspector.java:59)
       at com.instabug.library.InstabugFeedbackActivity.onCreate(InstabugFeedbackActivity.java:162)
       at android.app.Activity.performCreate(Activity.java:6466)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2640)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2753)
       at android.app.ActivityThread.access$1100(ActivityThread.java:186)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1609)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:238)
       at android.app.ActivityThread.main(ActivityThread.java:6016)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:937)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:798)
Caused by java.lang.NoSuchFieldException: No field mView in class Landroid/view/ColorViewRootImpl; (declaration of 'android.view.ColorViewRootImpl' appears in /system/framework/framework.jar:classes2.dex)
       at java.lang.Class.getDeclaredField(Class.java)
       at com.instabug.library.d.c.a.a(FieldHelper.java:82)
       at com.instabug.library.d.c.a.a(FieldHelper.java:54)
       at com.instabug.library.f.a.a.a(ActivityViewInspector.java:59)
       at com.instabug.library.InstabugFeedbackActivity.onCreate(InstabugFeedbackActivity.java:162)
       at android.app.Activity.performCreate(Activity.java:6466)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2640)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2753)
       at android.app.ActivityThread.access$1100(ActivityThread.java:186)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1609)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:238)
       at android.app.ActivityThread.main(ActivityThread.java:6016)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:937)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:798)
```

Instabug Android SDK version: 4.1.1.5-SNAPSHOT
Android version: 6.0
Phone: OPPO R9tm

**Comment by tarek360** [comment]
Hi @gejiaheng
Is this crash happens only on this phone? is this happening periodically?

**Comment by gejiaheng** [comment]
@tarek360 
We have 7000 updates in our gated launch yesterday and only one crash happened. But we have millions of daily active users, so it's still a notable crash.

**Comment by tarek360** [comment]
@gejiaheng The issue is fixed and this is a custom build
```
  compile 'com.instabug.library:instabug:4.2.0.1-SNAPSHOT'
```
Thank you.

**Comment by gejiaheng** [comment]
@tarek360 
Thanks so much for your quick work.
