### ISSUE TITLE
ArrayIndexOutOfBoundsException in AnalyticsObserver

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#45]
We have three crashes in our gated launch yesterday, all three happened on Huawei Phone Android 7.0.

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=22; index=22
       at java.util.ArrayList.add(ArrayList.java:442)
       at com.instabug.library.analytics.AnalyticsObserver.catchApiUsage(AnalyticsObserver.java:89)
       at com.instabug.library.analytics.AnalyticsObserver.catchApiUsage(AnalyticsObserver.java:70)
       at com.instabug.library.Instabug.getAppToken(Instabug.java:637)
       at com.instabug.library.network.NetworkManager.buildRequest(NetworkManager.java:137)
       at com.instabug.library.network.NetworkManager.buildRequest(NetworkManager.java:120)
       at com.instabug.library.network.NetworkManager.buildRequest(NetworkManager.java:112)
       at com.instabug.library.messaging.a.a.a(MessagingService.java:206)
       at com.instabug.library.messaging.b.a.a(SynchronizationManager.java:128)
       at com.instabug.library.messaging.b.a.a(SynchronizationManager.java:39)
       at com.instabug.library.messaging.b.a$a.run(SynchronizationManager.java:242)
       at android.os.Handler.handleCallback(Handler.java:755)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6524)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

Instabug Android SDK: 4.2.0.1-SNAPSHOT

**Comment by tarek360** [comment]
Hi @gejiaheng 
Thank you for this report, I will check it.

**Comment by tarek360** [comment]
@gejiaheng I think it was a rare case but it is fixed now and this is a custom build.
```
  compile 'com.instabug.library:instabug:4.2.0.2-SNAPSHOT'
```
Thank you.

**Comment by gejiaheng** [comment]
@tarek360 
Thank you so much!

**Comment by gejiaheng** [comment]
Still happening. About 40 crashes per day.

**Comment by vezikon** [comment]
@gejiaheng Can you provide us with the version number of Instabug that you are currently using?

**Comment by gejiaheng** [comment]
@vezikon We are currently using 4.2.0.5-SNAPSHOT.

**Comment by randaelbaz** [comment]
@gejiaheng Hi here is an update regarding this issue, the latest version(4.2.9) of the SDK contains the fix for this issue. I will close this issue, for now, please reopen if the problem still persists.
