### ISSUE TITLE
CursorWindowAllocationException in InstabugUserEventLogger

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#46]
We had 2 crashes in our gated launch yesterday.

```
Fatal Exception: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
       at android.database.CursorWindow.<init>(CursorWindow.java:108)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
       at com.instabug.library.logging.InstabugUserEventLogger.getEventLoggingCount(InstabugUserEventLogger.java:150)
       at com.instabug.library.logging.InstabugUserEventLogger.incrementEventLoggingCount(InstabugUserEventLogger.java:125)
       at com.instabug.library.logging.InstabugUserEventLogger.logUserEvent(InstabugUserEventLogger.java:63)
       at com.instabug.library.Instabug.logUserEvent(Instabug.java:1164)
       at com.zhihu.android.app.util.instabug.InstabugUtils.onFragmentShow(InstabugUtils.java:98)
       at com.zhihu.android.app.ui.fragment.BaseFragment.onScreenDisplaying(BaseFragment.java:164)
       at com.zhihu.android.app.ui.activity.MainActivity.onBackStackChanged(MainActivity.java:439)
       at android.support.v4.app.FragmentManagerImpl.reportBackStackChanged(FragmentManager.java:2473)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2176)
       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5461)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

I've found a related question in StackOverflow:  
https://stackoverflow.com/questions/21219039/android-database-cursorwindowallocationexception-when-moving-a-cursor

Instabug Android SDK: 4.2.0.2-SNAPSHOT

**Comment by tarek360** [comment]
Hi @gejiaheng ,
Thank you for this report, I will check it.

**Comment by tarek360** [comment]
Hi @gejiaheng we are working on this, and I will inform you when we release it, also please inform me if it is occurring in high rate.
Thank you.

**Comment by tarek360** [comment]
Hi @gejiaheng

I have read the StackOverflow question and already all cursors created are being closed
may be you use `Instabug.logUserEvent();` within a loop or similar something, anyway we have done some optimization in our code, you can use the SNAPSHOT and if the issue has appeared again please tell us.

```gradle
compile 'com.instabug.library:instabug:4.2.0.5-SNAPSHOT'
```

Thank you.

**Comment by gejiaheng** [comment]
@tarek360 
Thanks for your work.
