### ISSUE TITLE
RuntimeException in InstabugMessageUploaderService

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#47]
We had 3 crashes of this type in our gated launch yesterday.

```
Fatal Exception: java.lang.RuntimeException: Unable to start service com.instabug.library.messaging.InstabugMessageUploaderService@f36bc20 with Intent { cmp=com.zhihu.android/com.instabug.library.messaging.InstabugMessageUploaderService }: java.lang.RuntimeException: android.os.DeadSystemException
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3375)
       at android.app.ActivityThread.-wrap21(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1586)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6153)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
Caused by java.lang.RuntimeException: android.os.DeadSystemException
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3370)
       at android.app.ActivityThread.-wrap21(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1586)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6153)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
Caused by android.os.DeadSystemException
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3370)
       at android.app.ActivityThread.-wrap21(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1586)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6153)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
```

Instabug Android SDK: 4.2.0.2-SNAPSHOT

**Comment by tarek360** [comment]
Hi @gejiaheng ,
I will check it too.

**Comment by tarek360** [comment]
@gejiaheng 
I can't reproduce it, if you have clear steps to reproduce it, please tell me.

**Comment by gejiaheng** [comment]
@tarek360 
I don't know exact user steps neither. We'll see if this crash keep coming up or just be in a low amount.

**Comment by tarek360** [comment]
Hi @gejiaheng is the crash has a high occurrences?

**Comment by gejiaheng** [comment]
@tarek360 
No, we only had one more crash. I think it's OK if we don't fix this temporarily.
