### ISSUE TITLE
Failed to change locale for db '/data/data/com.zhihu.android/databases/instabug.db' to 'zh_CN'

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#48]
We had 5 crashes of this exception in our gated launch over the weekend.

```
Fatal Exception: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/com.zhihu.android/databases/instabug.db' to 'zh_CN'.
       at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:402)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:223)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:198)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:836)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:821)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1286)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:268)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       at com.instabug.library.internal.storage.cache.a.c.a(SQLiteDatabaseWrapper.java:30)
       at com.instabug.library.internal.storage.cache.a.a.b(DatabaseManager.java:32)
       at com.instabug.library.logging.InstabugUserEventLogger.getEventLoggingCount(InstabugUserEventLogger.java:143)
       at com.instabug.library.logging.InstabugUserEventLogger.incrementEventLoggingCount(InstabugUserEventLogger.java:125)
       at com.instabug.library.logging.InstabugUserEventLogger.logUserEvent(InstabugUserEventLogger.java:63)
       at com.instabug.library.Instabug.logUserEvent(Instabug.java:1164)
       at com.zhihu.android.app.util.instabug.InstabugUtils.onFragmentShow(InstabugUtils.java:98)
       at com.zhihu.android.app.ui.fragment.BaseFragment.onScreenDisplaying(BaseFragment.java:164)
       at com.zhihu.android.app.ui.fragment.ParentFragment.onBackStackChanged(ParentFragment.java:127)
       at android.support.v4.app.FragmentManagerImpl.reportBackStackChanged(FragmentManager.java:2473)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2176)
       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:823)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:776)
       at com.zhihu.android.app.ui.fragment.ParentFragment.onBackPressed(ParentFragment.java:147)
       at com.zhihu.android.app.ui.activity.MainActivity.onBackPressed(MainActivity.java:1823)
       at com.zhihu.android.app.ui.activity.MainActivity.onBackPressed(MainActivity.java:1773)
       at android.app.Activity.onKeyUp(Activity.java:2527)
       at com.zhihu.android.app.ui.activity.BaseActivity.onKeyUp(BaseActivity.java:109)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2689)
       at android.app.Activity.dispatchKeyEvent(Activity.java:2788)
       at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:541)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:319)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2424)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4642)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4598)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4082)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4135)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4101)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4238)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4109)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4295)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4082)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4135)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4101)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4109)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4082)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4135)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4101)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4271)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4457)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2359)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1983)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1974)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2336)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:148)
       at android.os.Looper.loop(Looper.java:151)
       at android.app.ActivityThread.main(ActivityThread.java:5826)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
Caused by android.database.sqlite.SQLiteDatabaseCorruptException: file is encrypted or is not a database (code 26)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:564)
       at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:376)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:223)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:198)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:836)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:821)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1286)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:268)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       at com.instabug.library.internal.storage.cache.a.c.a(SQLiteDatabaseWrapper.java:30)
       at com.instabug.library.internal.storage.cache.a.a.b(DatabaseManager.java:32)
       at com.instabug.library.logging.InstabugUserEventLogger.getEventLoggingCount(InstabugUserEventLogger.java:143)
       at com.instabug.library.logging.InstabugUserEventLogger.incrementEventLoggingCount(InstabugUserEventLogger.java:125)
       at com.instabug.library.logging.InstabugUserEventLogger.logUserEvent(InstabugUserEventLogger.java:63)
       at com.instabug.library.Instabug.logUserEvent(Instabug.java:1164)
       at com.zhihu.android.app.util.instabug.InstabugUtils.onFragmentShow(InstabugUtils.java:98)
       at com.zhihu.android.app.ui.fragment.BaseFragment.onScreenDisplaying(BaseFragment.java:164)
       at com.zhihu.android.app.ui.fragment.ParentFragment.onBackStackChanged(ParentFragment.java:127)
       at android.support.v4.app.FragmentManagerImpl.reportBackStackChanged(FragmentManager.java:2473)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2176)
       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:823)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:776)
       at com.zhihu.android.app.ui.fragment.ParentFragment.onBackPressed(ParentFragment.java:147)
       at com.zhihu.android.app.ui.activity.MainActivity.onBackPressed(MainActivity.java:1823)
       at com.zhihu.android.app.ui.activity.MainActivity.onBackPressed(MainActivity.java:1773)
       at android.app.Activity.onKeyUp(Activity.java:2527)
       at com.zhihu.android.app.ui.activity.BaseActivity.onKeyUp(BaseActivity.java:109)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2689)
       at android.app.Activity.dispatchKeyEvent(Activity.java:2788)
       at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:541)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:319)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2424)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4642)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4598)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4082)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4135)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4101)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4238)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4109)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4295)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4082)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4135)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4101)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4109)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4082)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4135)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4101)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4271)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4457)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2359)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1983)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1974)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2336)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:148)
       at android.os.Looper.loop(Looper.java:151)
       at android.app.ActivityThread.main(ActivityThread.java:5826)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
```
![image](https://user-images.githubusercontent.com/3777021/27527387-11a5a46a-5a7e-11e7-852d-ccb0dc1d939c.png)

Instabug Android SDK: 4.2.0.2-SNAPSHOT

**Comment by tarek360** [comment]
Hi @gejiaheng  I will check it and feedback you, thanks.

**Comment by tarek360** [comment]
@gejiaheng Have you a database in your app? are you trying to setLocale to it?

**Comment by tarek360** [comment]
@gejiaheng Have you a database in your app? have you set a new Locale to it somewhere?

**Comment by gejiaheng** [comment]
@tarek360 
We are using SQLite and Realm at the same time. As for SQLite, we do not set a new Locale to it anywhere.

**Comment by vezikon** [comment]
@gejiaheng we have made a custom build for you that we believe that it has a fix for this issue. 
Please, try out this snapshot: 

```
  compile 'com.instabug.library:instabug:4.2.6.2-SNAPSHOT'
```

**Comment by gejiaheng** [comment]
@vezikon Thanks, I'll try it.
