### ISSUE TITLE
Crash on InstabugSessionUploaderService

### ISSUE THREAD

**Issue by armen301** [Instabug/android-sample#49]
> java.lang.RuntimeException: Unable to start service com.instabug.library.InstabugSessionUploaderService@b625e08 with Intent { cmp=com.myPackage/com.instabug.library.InstabugSessionUploaderService }: java.lang.RuntimeException: android.os.DeadSystemException
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3347)
	at android.app.ActivityThread.-wrap21(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1583)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6154)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

The exception has occurred in version 2.6.2

**Comment by tarek360** [comment]
Hi @armen301,

The latest version is 4.2.2, please update to it, it is more stable and has a lot of the new features, and let me know if the issue still exists.

Thank you.

**Comment by vezikon** [comment]
Hello @armen301 Do you still have this issue with instabug?
