### ISSUE TITLE
Black/ empty screenshot and out of memory exception when using SurfaceView.

### ISSUE THREAD

**Issue by marcel-eggum** [Instabug/android-sample#50]
Good morning. I want to report an issue with the instabug Android SDK . We see that certain users cannot provide us with a screenshot / feedback. The screenshot that the SDK attempts to capture, is simply black and empty, and the SDK itself crashes after a few seconds with the following statement:

```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                     at rx.a.b.b$b.run(LooperScheduler.java:114)
                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                  Caused by: java.lang.OutOfMemoryError: Failed to allocate a 221965932 byte allocation with 16777216 free bytes and 195MB until OOM
                                                     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                     at android.graphics.Bitmap.nativeCreate(Native Method)
                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:915)
                                                     at com.instabug.library.f.a.a.a.a(BitmapUtils.java:88)
                                                     at com.instabug.library.f.a.a.a.d(BitmapUtils.java:76)
                                                     at com.instabug.library.f.a.a.a.c(BitmapUtils.java:40)
                                                     at com.instabug.library.f.a.a.a.b(BitmapUtils.java:21)
                                                     at com.instabug.library.f.a.a.a$1.a(BitmapUtils.java:27)
                                                     at com.instabug.library.f.a.a.a$1.call(BitmapUtils.java:24)
                                                     at rx.internal.operators.e.a(OnSubscribeDefer.java:46)
                                                     at rx.internal.operators.e.a(OnSubscribeDefer.java:35)
                                                     at rx.c.a(Observable.java:10150)
                                                     at rx.internal.operators.u$1.a(OperatorSubscribeOn.java:94)
                                                     at rx.a.b.b$b.run(LooperScheduler.java:107)
                                                     at android.os.Handler.handleCallback(Handler.java:751) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                     at android.os.Looper.loop(Looper.java:154) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6776) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
```
We are currently running instabug:4.2.6

That screen has some complex visual elements, and I therefore wonder, is there any settings we could tweak that would allow the Instabug SDK to actually capture the screen? 
It seems to work on other screens in the app, but not when we are trying to capture the complex visualization.

The visualization itself consists of a simple ViewGroup with custom views that we position. Additionally, OpenGL is sometimes used to render rain.

![screenshot_20170725-095333](https://user-images.githubusercontent.com/1391423/28561929-99e7f1f8-7120-11e7-9397-82796523b031.png)
![screenshot_20170725-095115](https://user-images.githubusercontent.com/1391423/28561930-9a093c32-7120-11e7-905d-fb1654251a95.png)

**Comment by tarek360** [comment]
Hi @marcel-eggum ,
Thank you for reporting this issue، I know that you have contacted with our happiness team, let's keep this issue open till we get a fix, thanks.

**Comment by reemalashry1** [comment]
Hello @marcel-eggum 
The fix for this issue is released in version: 4.2.9
Kindly check it [here](https://github.com/Instabug/android-sample/commit/0031190b357cd02b4c8e887b7f200be6c956a4c2)
I have also renamed the issue to be more relevant to anyone using SurfaceView.

**Comment by melbic** [comment]
We actually still have the issue in version `com.instabug.library:instabug:4.3.1.2-SNAPSHOT`.
![screenshot_20171006-084349](https://user-images.githubusercontent.com/186461/31266218-0c0a4336-aa73-11e7-8ec4-01daa4ee7b91.png)

The black view is `SurfaceView`.  Do we have to set any custom property to enable screenshots for that this views? Didn't see anything in the release notes.

**Comment by reemalashry1** [comment]
Hey @melbic aer you using `GLSurfaceView` or `SurfaceView`? As we don't support `SurfaceView`

**Comment by melbic** [comment]
Ok, I understand. The view is from Unity, so we actually don't really have a choice. Thanks for your answer.

**Comment by sfseyhan** [comment]
Is there any plan to support SurfaceView? We are using a 3rd party library that has a SurfaceView and the SurfaceView is black in all recordings.

**Comment by mgood7123** [comment]
any progress?
