### ISSUE TITLE
Crash caused by SQLiteDatebase

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#56]
```
58.630 14944-15529/com.zhihu.android E/AndroidRuntime: FATAL EXCEPTION: Thread-2405
                                                                   Process: com.zhihu.android, PID: 14944
                                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.sqlite.SQLiteStatement android.database.sqlite.SQLiteDatabase.compileStatement(java.lang.String)' on a null object reference
                                                                       at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:831)
                                                                       at android.database.DatabaseUtils.queryNumEntries(DatabaseUtils.java:810)
                                                                       at android.database.DatabaseUtils.queryNumEntries(DatabaseUtils.java:778)
                                                                       at com.instabug.library.internal.storage.cache.a.d.b(SQLiteDatabaseWrapper.java:88)
                                                                       at com.instabug.library.l.h(SessionManager.java:112)
                                                                       at com.instabug.library.l.a(SessionManager.java:49)
                                                                       at com.instabug.library.l$1.run(SessionManager.java:95)
                                                                       at java.lang.Thread.run(Thread.java:818)
08-03 10:20:58.630 14944-15555/com.zhihu.android E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
08-03 10:20:58.660 14944-15500/com.zhihu.android E/SoundPool: void android::Soundpool_perf_lock_release(): Perf lock release error 
08-03 10:20:58.950 9206-9220/? E/Launcher.DynamicWeatherIcon: can not get weather data, so just display defalut icon
08-03 10:20:59.620 1481-1898/? E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=246, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
08-03 10:21:00.010 9206-9220/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_hour.png: open failed: ENOENT (No such file or directory)
08-03 10:21:00.010 9206-9220/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_minute.png: open failed: ENOENT (No such file or directory)
08-03 10:21:00.010 9206-9220/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial.png: open failed: ENOENT (No such file or directory)
08-03 10:21:00.010 9206-9220/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/bbkcore/theme/icons/dynamic_icon/com.android.BBKClock/res/drawable-sw360dp-xxhdpi/clock_dial_center.png: open failed: ENOENT (No such file or directory)
08-03 10:21:01.000 15583-15635/com.zhihu.android E/GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
08-03 10:21:02.890 15583-15659/com.zhihu.android E/SQLiteLog: (14) cannot open file at line 31278 of [2ef4f3a5b1]
08-03 10:21:02.890 15583-15659/com.zhihu.android E/SQLiteLog: (14) os_unix.c:31278: (2) open(/data/user/0/com.zhihu.android/databases/instabug.db) - 
08-03 10:21:02.890 15583-15659/com.zhihu.android E/SQLiteDatabase: Failed to open database '/data/user/0/com.zhihu.android/databases/instabug.db'.
                                                                   android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
                                                                       at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
                                                                       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
                                                                       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:199)
                                                                       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
                                                                       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                                                                       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                       at com.instabug.library.internal.storage.cache.a.c.b(InstabugSQLiteOpenHelper.java:140)
                                                                       at com.instabug.library.internal.storage.cache.a.c.a(InstabugSQLiteOpenHelper.java:111)
                                                                       at com.instabug.library.internal.storage.cache.a.d.a(SQLiteDatabaseWrapper.java:29)
                                                                       at com.instabug.library.internal.storage.cache.a.a.b(DatabaseManager.java:30)
                                                                       at com.instabug.library.logging.a.b(InstabugLogDbHelper.java:83)
                                                                       at com.instabug.library.logging.a.a(InstabugLogDbHelper.java:31)
                                                                       at com.instabug.library.logging.a$1.a(InstabugLogDbHelper.java:57)
                                                                       at com.instabug.library.logging.a$1.onNext(InstabugLogDbHelper.java:42)
                                                                       at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
                                                                       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
                                                                       at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
                                                                       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)
```

OR
```
Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error(Sqlite code 14): Could not open database,(OS error - 2:No such file or directory)
       at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:819)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:804)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:707)
       at com.instabug.library.internal.storage.cache.a.c.b(InstabugSQLiteOpenHelper.java:140)
       at com.instabug.library.internal.storage.cache.a.c.a(InstabugSQLiteOpenHelper.java:111)
       at com.instabug.library.internal.storage.cache.a.d.a(SQLiteDatabaseWrapper.java:29)
       at com.instabug.library.internal.storage.cache.a.a.b(DatabaseManager.java:30)
       at com.instabug.library.l.h(SessionManager.java:110)
       at com.instabug.library.l.a(SessionManager.java:49)
       at com.instabug.library.l$1.run(SessionManager.java:95)
       at java.lang.Thread.run(Thread.java:831)
```

App crashes immediately while launching. This bug happens 100% on some phones including Vivo X9 (Android 6.0.1)

Instabug Android SDK: 4.2.6.2-SNAPSHOT

The bug doesn't exist when I revert to the last version we use which is 4.2.0.5-SNAPSHOT.

**Comment by tarek360** [comment]
Hi @gejiaheng,
I will check it and get back to you, thanks.

**Comment by tarek360** [comment]
@gejiaheng In the stack trace I see other errors related to the resources and the disk in your app, anyway I'm investigating the issue, until I finish please try this `4.2.6.8-SNAPSHOT`, it may help.
Thank you.

**Comment by gejiaheng** [comment]
@tarek360 `4.2.6.8-SNAPSHOT` works fine.
