### ISSUE TITLE
OnErrorNotImplementedException

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#57]
```
Fatal Exception: rx.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.query(java.lang.String, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String, java.lang.String, java.lang.String)' on a null object reference
       at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
       at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
       at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
       at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:152)
       at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
       at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:205)
       at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
       at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:305)
       at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:220)
       at rx.subjects.PublishSubject.onNext(PublishSubject.java:73)
       at com.instabug.library.core.eventbus.a.a(EventBus.java:24)
       at com.instabug.library.core.eventbus.coreeventbus.b.a(SDKCoreEventPublisher.java:9)
       at com.instabug.library.l.a(SessionManager.java:238)
       at com.instabug.library.l.k(SessionManager.java:204)
       at com.instabug.library.l.c(SessionManager.java:140)
       at com.instabug.library.l.a(SessionManager.java:274)
       at com.instabug.library.tracking.b.onReceive(CurrentActivityLifecycleChanged.java:25)
       at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:308)
       at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
       at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:118)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5628)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.query(java.lang.String, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String, java.lang.String, java.lang.String)' on a null object reference
       at com.instabug.library.internal.storage.cache.a.d.a(SQLiteDatabaseWrapper.java:78)
       at com.instabug.library.logging.InstabugUserEventLogger.getEventLoggingCount(InstabugUserEventLogger.java:163)
       at com.instabug.library.logging.InstabugUserEventLogger.incrementEventLoggingCount(InstabugUserEventLogger.java:144)
       at com.instabug.library.logging.InstabugUserEventLogger.access$100(InstabugUserEventLogger.java:30)
       at com.instabug.library.logging.InstabugUserEventLogger$1.a(InstabugUserEventLogger.java:186)
       at com.instabug.library.logging.InstabugUserEventLogger$1.call(InstabugUserEventLogger.java:180)
       at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
       at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
       at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:305)
       at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:220)
       at rx.subjects.PublishSubject.onNext(PublishSubject.java:73)
       at com.instabug.library.core.eventbus.a.a(EventBus.java:24)
       at com.instabug.library.core.eventbus.coreeventbus.b.a(SDKCoreEventPublisher.java:9)
       at com.instabug.library.l.a(SessionManager.java:238)
       at com.instabug.library.l.k(SessionManager.java:204)
       at com.instabug.library.l.c(SessionManager.java:140)
       at com.instabug.library.l.a(SessionManager.java:274)
       at com.instabug.library.tracking.b.onReceive(CurrentActivityLifecycleChanged.java:25)
       at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:308)
       at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
       at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:118)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5628)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
```

Instabug SDK: 4.2.6.2-SNAPSHOT

**Comment by vezikon** [comment]
Hi @gejiaheng, do you still get this crash with SDK version 4.2.6.8-SNAPSHOT?

**Comment by reemalashry1** [comment]
Hello @gejiaheng 

The fix for this issue is released with version: 4.2.9
Kindly check it [here](https://github.com/Instabug/android-sample/commit/0031190b357cd02b4c8e887b7f200be6c956a4c2)

**Comment by rafael-labela** [comment]
Able to replicate it on 4.11.1 Essencial products PH-1 Android 10

**Comment by desgraci** [comment]
Able to replicate it on 4.11.1 Essencial products PH-1 Android 10
