### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by YShein** [Instabug/android-sample#62]
Hello, i have received this on samsung galaxy s4

Fatal Exception: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
       at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 4752152 free bytes and 4MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:832)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:757)
       at com.instabug.library.f.a.a.a.a(BitmapUtils.java:118)
       at com.instabug.library.f.a.a.a.d(BitmapUtils.java:78)
       at com.instabug.library.f.a.a.a.c(BitmapUtils.java:37)
       at com.instabug.library.f.a.a.a.b(BitmapUtils.java:21)
       at com.instabug.library.f.a.a.a$1.a(BitmapUtils.java:27)
       at com.instabug.library.f.a.a.a$1.call(BitmapUtils.java:24)
       at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
       at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
       at rx.Observable.unsafeSubscribe(Observable.java:10346)
       at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
       at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194`

**Comment by reemalashry1** [comment]
Hello @YShein  
would you please tell me, on which version of the SDK does this happen?

**Comment by YShein** [comment]
Hello @reemalashry1 
It was 4.2.9

**Comment by reemalashry1** [comment]
@YShein thank you, we will be checking this and I'll get back to you 👍

**Comment by reemalashry1** [comment]
Hey @YShein 
we have made a snapshot that fixes the issue, please use: 4.2.10.4-SNAPSHOT

**Comment by YShein** [comment]
I received same issue from Galaxy S4 

Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.OutOfMemoryError: Failed to allocate a 2073612 byte allocation with 1133696 free bytes and 1107KB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.BitmapFactory.nativeDecodeStream(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:752)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:728)
       at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:477)
       at com.instabug.library.util.a.a(BitmapUtils.java:182)
       at com.instabug.library.util.b.a(BitmapWorkerTask.java:47)
       at com.instabug.library.util.b.doInBackground(BitmapWorkerTask.java:13)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

Instabug version 4.2.9

**Comment by reemalashry1** [comment]
Hey @YShein have you tried  4.2.10.4-SNAPSHOT ?
For building snapshot releases add this to your app-level build.gradle file:

```
repositories {
 maven {
 url "https://oss.sonatype.org/content/repositories/snapshots"
 }
}
```

Kindly use the snapshot and let me know how it goes.

**Comment by fleficher** [comment]
Hi, same here using version 3.9.4-SNAPSHOT

**Comment by bikranttripathi** [comment]
Hi @reemalashry1 , I'm also seeing OOM in the latest version (**4.3.3**)

Device Information:
Model: **SM-G955U**
Android Version: **7.0**

```
Fatal Exception: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
       at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by java.lang.OutOfMemoryError: Failed to allocate a 348353292 byte allocation with 8795578 free bytes and 243MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:915)
       at com.instabug.library.f.a.a.a.a(BitmapUtils.java:90)
       at com.instabug.library.f.a.a.a.d(BitmapUtils.java:78)
       at com.instabug.library.f.a.a.a.c(BitmapUtils.java:39)
       at com.instabug.library.f.a.a.a.b(BitmapUtils.java:23)
       at com.instabug.library.f.a.a.a$1.a(BitmapUtils.java:29)
       at com.instabug.library.f.a.a.a$1.call(BitmapUtils.java:26)
       at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
       at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
       at rx.Observable.unsafeSubscribe(Observable.java:10150)
       at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
       at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by ZiadAyman** [comment]
hey @bikranttripathi 

Can you tell me please if you are experiencing this consistently or it's a one time occurrence?

**Comment by ZiadAyman** [comment]
hey @bikranttripathi 

I am following up with you. Are you still experiencing the same issue?

**Comment by bikranttripathi** [comment]
@ZiadAyman Sorry for the delayed reply. 

It looks like it was a one-time thing. I haven't seen this crash in a while

**Comment by bikranttripathi** [comment]
@ZiadAyman I have a question that's not related to this thread. 

Is there a way to check latest changelogs for instabug?

**Comment by ZiadAyman** [comment]
Hey @bikranttripathi yes you can check the latest changelogs from your dashboard as shown in the screenshot :) 
<img width="1280" alt="screen shot 2017-12-24 at 1 06 29 pm" src="https://user-images.githubusercontent.com/15649292/34326004-73b48b92-e8ab-11e7-9873-32ff570d6278.png">

**Comment by bikranttripathi** [comment]
Thanks again :)

**Comment by ZiadAyman** [comment]
Always a pleasure.
