### ISSUE TITLE
Instabug.getLocale NullPointerException

### ISSUE THREAD

**Issue by fleficher** [Instabug/android-sample#65]
Hi,

We have some reports on crashlytics about NPEs in InstabugFeedbackActivity :

```java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Locale com.instabug.library.g.b.a(android.content.Context)' on a null object reference
       at com.instabug.library.g.d.b(SourceFile:150)
       at com.instabug.library.Instabug.getLocale(SourceFile:847)
       at com.instabug.library.InstabugFeedbackActivity.onCreate(SourceFile:119)
       at android.app.Activity.performCreate(Activity.java:6955)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

Version : 3.9.3-SNAPSHOT

**Comment by reemalashry1** [comment]
Hey @fleficher thank you for reporting this, we will look into it and I'll get back to you  👍

**Comment by reemalashry1** [comment]
Hey @fleficher Would you please send me a full stack trace for the crash? Also, are you able to reproduce this crash? If yes, do you mind sharing some steps to help reproducing it please? 
Thanks!

**Comment by fleficher** [comment]
Hi @reemalashry1  here is the full strack trace : [stacktrace.txt](https://github.com/Instabug/android-sample/files/1386567/stacktrace.txt)

I couldn't reproduce this crash yet; It seems to impact all version of Android

**Comment by reemalashry1** [comment]
Hey @fleficher we have fixed the issue and made a snapshot for you, kindly use 3.9.4-SNAPSHOT
To use the snapshot, please add the following lines to your app-level `build.gradle` file:

```dependencies {
 compile 'com.instabug.library:instabug:3.9.4-SNAPSHOT'
}
```


```repositories {
   maven {
       //  add this only if interested in getting SNAPSHOT releases
       url "https://oss.sonatype.org/content/repositories/snapshots"
   }
}```

Let me know how it goes :)

**Comment by reemalashry1** [comment]
Hey @fleficher we have fixed the issue and made a snapshot for you, kindly use 3.9.4-SNAPSHOT


To use the snapshot, please add the following lines to your app-level `build.gradle` file:

```
dependencies {
 compile 'com.instabug.library:instabug:3.9.4-SNAPSHOT'
}

repositories {
   maven {
       //  add this only if interested in getting SNAPSHOT releases
       url "https://oss.sonatype.org/content/repositories/snapshots"
   }
}

Let me know how it goes :)

**Comment by fleficher** [comment]
@reemalashry1 Great thank you ! I will let you know if it worked

**Comment by fleficher** [comment]
Hi, the crash is still present in 3.9.4.4-SNAPSHOT

**Comment by ZiadAyman** [comment]
Hey @fleficher I'll pass this again to our Android team and I'll get back to you with the updates :)

**Comment by ZiadAyman** [comment]
Hey @fleficher Can you tell me which Android OS are you currently using and this problem is occuring on?

**Comment by fleficher** [comment]
Hu @ZiadAyman this crash is occuring on devices from 4.1.2 to 8.0.0
Here the full stacktrace using the last version :
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp/com.instabug.library.InstabugFeedbackActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Locale com.instabug.library.g.b.a(android.content.Context)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5461)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Locale com.instabug.library.g.b.a(android.content.Context)' on a null object reference
       at com.instabug.library.g.d.b(SourceFile:150)
       at com.instabug.library.Instabug.getLocale(SourceFile:847)
       at com.instabug.library.InstabugFeedbackActivity.onCreate(SourceFile:119)
       at android.app.Activity.performCreate(Activity.java:6251)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5461)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
``` 

Is there a way that the `InstabugFeedbackActivity` get launched before the sdk is initialized ?
We don't initialize the SDK at app startup but more lately in the app because we dont want it to be enabled for all users.

**Comment by ZiadAyman** [comment]
@fleficher Can you tell me please where do you exactly initialize your SDK in your code? I get it's lately in the app for specific users. Can I have more details, please?

**Comment by fleficher** [comment]
We initialize the SDK after the user log in, we call the following methods then :

```
new Builder(application, BuildConfig.INSTABUG_TOKEN)
                .setCrashReportingState(State.DISABLED)
                .setInAppMessagingState(State.DISABLED)
                .setPushNotificationState(State.DISABLED)
                .setSurveysState(State.ENABLED)
                .setViewHierarchyState(State.DISABLED)
                .build();
        Instabug.setAttachmentTypesEnabled(true, false, false, false, false);
        Instabug.setEmailFieldRequired(false);
        Instabug.setEmailFieldVisibility(false);
        Instabug.setCommentFieldRequired(true);
        Instabug.setShakingThreshold(750);
```
Nothing really special.

**Comment by fleficher** [comment]
I've succeed to reproduce this crashby using an adb command : `am start -a android.intent.action.VIEW -d instabug://instabug.com` to force the display of the activity.

If this get called before the SDK is initialized, it crashs (for example when the app is killed)

**Comment by ZiadAyman** [comment]
So @fleficher Instabug should be initialized in Application class in order to avoid any misbehavior with the SDK. For your use case we recommend that you initialize the SDK on the application class and then follow it by calling `Instabug.disable()` and then you can call `Insatbug.enable()` whenever a user logs in.

**Comment by fleficher** [comment]
@ZiadAyman Ok thank you, we will try this way

**Comment by ZiadAyman** [comment]
Hey @fleficher how is it going? All working good at your end?

**Comment by ZiadAyman** [comment]
hey @fleficher Please get back if you face any other problems. I will close the issue for now.
