### ISSUE TITLE
NullPointerException in InstabugFeedbackActivity

### ISSUE THREAD

**Issue by fleficher** [Instabug/android-sample#66]
Hi,

I've encountered the following crash during test :

```java
java.lang.NullPointerException: Attempt to invoke virtual method 'com.instabug.library.bugreporting.model.Bug com.instabug.library.bugreporting.model.Bug.a(com.instabug.library.bugreporting.model.Bug$Type)' on a null object reference
  at com.instabug.library.InstabugFeedbackActivity.d(InstabugFeedbackActivity.java:359)
  at com.instabug.library.InstabugFeedbackActivity.a(InstabugFeedbackActivity.java:317)
  at com.instabug.library.i.a.b.b.onClick(InvocationFragment.java:95)
  at android.view.View.performClick(View.java:5697)
  at android.view.View$PerformClick.run(View.java:22526)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:158)
  at android.app.ActivityThread.main(ActivityThread.java:7225)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Using version** : 3.9.4-SNAPSHOT

**Steps to reproduce** : 
1. Shake the device
2. Before the dialog appears, start another activity
3. The 2nd activity is started & show the Instabug Dialog
4. Dismiss it & go the to previous activity
5. Another dialog is shown
6. Click on an item -> Crash appears

**Comment by reemalashry1** [comment]
Thank you for reporting this and for the repro steps.
We will be checking it and I’ll get back to you.

**Comment by reemalashry1** [comment]
Hey @fleficher we have fixed the issue and made a snapshot for you, kindly use `3.9.4.1-SNAPSHOT`
To use the snapshot, please add the following lines to your app-level `build.gradle` file:

```
dependencies {
compile 'com.instabug.library:instabug:3.9.4.1-SNAPSHOT'
}

repositories {
  maven {
      //  add this only if interested in getting SNAPSHOT releases
      url "https://oss.sonatype.org/content/repositories/snapshots"
  }
}

**Comment by fleficher** [comment]
@reemalashry1 Great it's working ! Thanks a lot
