### ISSUE TITLE
Crash: IndexOutOfBoundsException at SurveyActivity.onBackPressed

### ISSUE THREAD

**Issue by fleficher** [Instabug/android-sample#72]
Hi,

We've got some IndexOutOfBoundsException with the sdk from crashlytics :
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 0
       at java.util.Collections$EmptyList.get(Collections.java:3690)
       at com.instabug.survey.ui.SurveyActivity.onBackPressed(SourceFile:63)
       at android.app.Activity.onKeyUp(Activity.java:2868)
       at android.view.KeyEvent.dispatch(KeyEvent.java:3361)
       at android.app.Activity.dispatchKeyEvent(Activity.java:3169)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:466)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5041)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5003)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4532)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4585)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4551)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4684)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4559)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4741)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4532)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4585)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4551)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4559)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4532)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4585)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4551)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4717)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4886)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3091)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2625)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2616)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3068)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```
* Using 3.9.4.2-SNAPSHOT version

**Comment by ZiadAyman** [comment]
@fleficher I'll definitely communicate this with our Android team. Meanwhile, did you get the chance to try 3.9.4.4 SNAPSHOT?

**Comment by fleficher** [comment]
Hi @ZiadAyman , didn't have the chance to test it on production yet. I will let you know when it's done

**Comment by ZiadAyman** [comment]
@fleficher waiting for your updates regarding 3.9.4.4 SNAPSHOT :)
