### ISSUE TITLE
Crash: NullPointerException in State$Builder.getLocale

### ISSUE THREAD

**Issue by fleficher** [Instabug/android-sample#73]
Hello,

We've got some NPE with the sdk from crashlytics :

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
       at com.instabug.library.model.State$Builder.getLocale(SourceFile:731)
       at com.instabug.library.model.State$Builder.build(SourceFile:687)
       at com.instabug.library.bugreporting.model.Bug$a.a(SourceFile:312)
       at com.instabug.library.bugreporting.a.a(SourceFile:62)
       at com.instabug.library.invocation.b.a(SourceFile:301)
       at com.instabug.library.invocation.b.a(SourceFile:232)
       at com.instabug.library.invocation.a.e.c(SourceFile:36)
       at com.instabug.library.util.k.onSensorChanged(SourceFile:52)
       at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:837)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```
* Using 3.9.4.2-SNAPSHOT version

**Comment by ZiadAyman** [comment]
Hello @fleficher, did you get the chance to use 3.9.4.4 SNAPSHOT we sent yesterday? Does the crash still occur on 3.9.4.4?

**Comment by fleficher** [comment]
@ZiadAyman We're still using the 3.9.4.2 version on production. We're gonna update it today and i will tell you if it's ok

**Comment by ZiadAyman** [comment]
@fleficher yes please make sure to test with 3.9.4.4 and get back to me with the updates :)

**Comment by ZiadAyman** [comment]
@fleficher Hey there! Following up to know if everything is in place. Any updates?

**Comment by fleficher** [comment]
Hi @ZiadAyman sorry for the delay, the version 3.9.4.4 has fixed the bug.
Thank you
