### ISSUE TITLE
Crash caused by VisualUserSteps

### ISSUE THREAD

**Issue by gejiaheng** [Instabug/android-sample#77]
We update our Android Instabug  SDK to 4.9.0 in the latest release. Had thousands of crashes today caused by the visual user steps feature. Actually we didn't enable this feature. 

Trace:
```java
Caused by java.util.NoSuchElementException
       at java.util.LinkedList.getLast(LinkedList.java:257)
       at com.instabug.library.visualusersteps.c.b(VisualUserSteps.java:34)
       at com.instabug.library.visualusersteps.d.b(VisualUserStepsProvider.java:124)
       at com.instabug.library.visualusersteps.d.a(VisualUserStepsProvider.java:111)
       at com.instabug.library.tracking.InstabugInternalTrackingDelegate.handleActivityPausedEvent(InstabugInternalTrackingDelegate.java:155)
       at com.instabug.library.tracking.b.onActivityPaused(InstabugActivityLifecycleListener.java:30)
       at android.app.Application.dispatchActivityPaused(Application.java:230)
       at android.app.Activity.onPause(Activity.java:1655)
       at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:402)
       at com.trello.rxlifecycle2.components.support.RxAppCompatActivity.onPause(RxAppCompatActivity.java:81)
       at com.zhihu.android.base.ZHActivity.onPause(ZHActivity.java:88)
       at com.zhihu.android.app.ui.activity.BaseFragmentActivity.onPause(BaseFragmentActivity.java:74)
       at android.app.Activity.performPause(Activity.java:6996)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1323)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3799)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3776)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3750)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3724)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6326)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
```
![image](https://user-images.githubusercontent.com/3777021/35952215-f24a00f4-0cb9-11e8-8712-4089d5352259.png)

**Comment by ZiadAyman** [comment]
This is fixed in 4.9.1, please upgrade your SDK version and keep us posted if you still face the same problem.
