### ISSUE TITLE
java.lang.IllegalArgumentException: bad base-64

### ISSUE THREAD

**Issue by fluxxion82** [Instabug/android-sample#8]
I get this exception occasionally, usually after a crash in our app and then trying to open the app again. I was able to copy and save the stack trace today, so here it is:
```
09-07 12:14:42.581 5631-5631/io.company.android.dev I/MultiDex: VM has multidex support, MultiDex support library is disabled.
09-07 12:14:42.621 5631-5631/io.company.android.dev I/INSTABUG - Builder: Initializing Instabug v2.3.3
09-07 12:14:42.641 5631-5631/io.company.android.dev D/AndroidRuntime: Shutting down VM
09-07 12:14:42.641 5631-5631/io.company.android.dev E/INSTABUG - Instabug: Instabug Caught an Unhandled Exception: java.lang.RuntimeException
                                                                         java.lang.RuntimeException: Unable to create application io.company.android.CompanyApp: java.lang.IllegalArgumentException: bad base-64
                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6319)
                                                                             at android.app.ActivityThread.access$1800(ActivityThread.java:221)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:158)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                          Caused by: java.lang.IllegalArgumentException: bad base-64
                                                                             at android.util.Base64.decode(Base64.java:161)
                                                                             at android.util.Base64.decode(Base64.java:136)
                                                                             at android.util.Base64.decode(Base64.java:118)
                                                                             at com.instabug.library.internal.storage.cache.i.c(OnDiskCache.java:198)
                                                                             at com.instabug.library.internal.storage.cache.i.b(OnDiskCache.java:67)
                                                                             at com.instabug.library.internal.storage.cache.e.a(CacheManager.java:191)
                                                                             at com.instabug.library.internal.storage.cache.e.a(CacheManager.java:174)
                                                                             at com.instabug.library.internal.storage.cache.h.a(IssuesCacheManger.java:27)
                                                                             at com.instabug.library.internal.storage.cache.h.d(IssuesCacheManger.java:80)
                                                                             at com.instabug.library.internal.storage.cache.h.c(IssuesCacheManger.java:66)
                                                                             at com.instabug.library.i.y(InstabugDelegate.java:209)
                                                                             at com.instabug.library.i.<init>(InstabugDelegate.java:114)
                                                                             at com.instabug.library.Instabug$Builder.build(Instabug.java:946)
                                                                             at com.instabug.library.Instabug$Builder.build(Instabug.java:1024)
                                                                             at io.company.android.CompanyApp.onCreate(CompanyApp.java:109)
                                                                             at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6316)
                                                                             at android.app.ActivityThread.access$1800(ActivityThread.java:221) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:158) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
09-07 12:16:59.771 7044-7044/io.company.android.dev D/ResourcesManager: For user 0 new overlays fetched Null
09-07 12:16:59.781 7044-7044/io.company.android.dev I/InjectionManager: Inside getClassLibPath caller 
09-07 12:16:59.801 7044-7044/io.company.android.dev I/MultiDex: VM with version 2.1.0 has multidex support
09-07 12:16:59.801 7044-7044/io.company.android.dev I/MultiDex: install
09-07 12:16:59.801 7044-7044/io.company.android.dev I/MultiDex: VM has multidex support, MultiDex support library is disabled.
09-07 12:16:59.851 7044-7044/io.company.android.dev I/INSTABUG - Builder: Initializing Instabug v2.3.3
09-07 12:16:59.861 7044-7079/io.company.android.dev W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/io.company.android.dev/shared_prefs/instabug.xml.bak
```

This is the code block where the error originates, from our Application object,  (`io.company.android.CompanyApp.onCreate(CompanyApp.java:109)`):
```
new Instabug.Builder(this, "appToken")
                    .setInvocationEvent(IBGInvocationEvent.IBGInvocationEventNone)
                    .setCrashReportingState(Feature.State.ENABLED)
                    .setShouldShowIntroDialog(false)
                    .build();
```
When this exception happens, there's just a white screen until you close the app. Not sure if it's something on our side, or yours, but wanted to bring it up. The symptoms have been reported a few times, although I can't say exactly that this is the issue for certain, but I personally have seen this a couple times. If you have any insight, it would be appreciated.

**Comment by prithsharma** [comment]
I am seeing this too. Any resolutions?

**Comment by vezikon** [comment]
Please, upgrage to Instabug v2.6.2. This is issue if fixed in this version.

**Comment by pan-haos** [comment]
How did you fix it , I just face the same probleam with bad-base64 , I also use base64 decode a base-64,Ios can decode it ,but Android cannot

**Comment by rexhinokovaci** [comment]
anyone found any solution after 1  year?

**Comment by mzelzoghbi** [comment]
@rexhinokovaci Are you facing this issue on our latest SDK Version 9.1.6 ?

**Comment by rexhinokovaci** [comment]
yes and on 29 API level

**Comment by rexhinokovaci** [comment]
> @rexhinokovaci Are you facing this issue on our latest SDK Version 9.1.6 ?

yes and on 29 API level

**Comment by mzelzoghbi** [comment]
is it happening on native android SDK or ReactNative? And can you reproduce the issue locally?

**Comment by rexhinokovaci** [comment]
> is it happening on native android SDK or ReactNative? And can you reproduce the issue locally?

on native Android SDK I tried to debbug but not issue meanwhile on the Run : E/AndroidRuntime: FATAL EXCEPTION: main is spamming the logs. I tried to put some try - catch block but still no action and It will get back on the main activity

**Comment by mzelzoghbi** [comment]
Can you share with me the full stacktrace ?
