### ISSUE TITLE
MotionEvent NullPointerException

### ISSUE THREAD

**Issue by Viked** [Instabug/android-sample#83]
Hello, I have received an issue from fabric

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.MotionEvent.getRawX()' on a null object reference
       at com.instabug.library.d.a.a(MotionEventRecognizer.java:65)
       at com.instabug.library.d.a.a(MotionEventRecognizer.java:37)
       at com.instabug.library.d.a$b.onFling(MotionEventRecognizer.java:271)
       at android.view.GestureDetector.onTouchEvent(GestureDetector.java:667)
       at com.instabug.library.d.a.a(MotionEventRecognizer.java:59)
       at com.instabug.library.tracking.c.a(InstabugTouchEventsTracker.java:44)
       at com.instabug.library.tracking.InstabugInternalTrackingDelegate.trackTouchEvent(InstabugInternalTrackingDelegate.java:427)
       at com.instabug.library.tracking.b.a(InstabugTouchEventsHandler.java:24)
       at com.instabug.library.InstabugTrackingDelegate.notifyActivityGotTouchEvent(InstabugTrackingDelegate.java:130)
       at com.dartfleet.mobile.utils.bugtracker.InstabugTrackerImpl.dispatchTouchEvent(InstabugTrackerImpl.java:226)
       at com.dartfleet.mobile.utils.bugtracker.BugTrackerBridge.dispatchTouchEvent(BugTrackerBridge.java:49)
       at com.dartfleet.mobile.common.activities.BaseMvpActivity.dispatchTouchEvent(BaseMvpActivity.java:84)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:569)
       at android.view.View.dispatchPointerEvent(View.java:11008)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5162)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5014)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4592)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4558)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4691)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4566)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4748)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4592)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4558)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4566)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7098)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7030)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6991)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7208)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`

Device SM-G955F with android 7.0
Instabug sdk 4.12.1

**Comment by ZiadAyman** [comment]
Hey @Viked 
We are currently checking this for you and we'll get back asap! 

Thanks for reporting it.

**Comment by ZiadAyman** [comment]
Hey @Viked 
Please use 4.12.1.6-SNAPSHOT and let me know if the error still occurs. Thanks for your patience!

**Comment by araujotadeu** [comment]
@ZiadAyman I am using the version 8.0.9 and having the same problem. 

Samsung and Huawei devices, Android 7 and 8
