### ISSUE TITLE
Proguard issues (rx.subjects.PublishSubject)

### ISSUE THREAD

**Issue by MarkySmarky** [Instabug/android-sample#85]
Using 4.3.2 version and getting this in production:

Fatal Exception: java.lang.NoClassDefFoundError: rx.subjects.PublishSubject
       at com.instabug.library.core.eventbus.a.(HackersProtected:16)
       at com.instabug.library.core.eventbus.coreeventbus.a.(HackersProtected:8)
       at com.instabug.library.core.eventbus.coreeventbus.a.a(HackersProtected:14)
       at com.instabug.library.core.eventbus.coreeventbus.b.a(HackersProtected:9)
       at com.instabug.library.network.InstabugNetworkReceiver.onReceive(HackersProtected:38)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2669)
       at android.app.ActivityThread.access$1800(ActivityThread.java:170)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5635)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)

**Comment by ZiadAyman** [comment]
Hey @MarkySmarky. Checking this for you right away!

**Comment by ZiadAyman** [comment]
Hey @MarkySmarky. I double checked this for you. Seems like this piece of code no longer exists. Please upgrade to the latest android SDK version and let me know if you still face the same problem.
