### ISSUE TITLE
java.lang.NoClassDefFoundError: com.instabug.library.analytics.AnalyticsObserver

### ISSUE THREAD

**Issue by MohNage7** [Instabug/android-sample#86]
Hello, 
I'm facing the following bug after upgrading from Firebase Crash reporting to Firebase Crashlytics. And  i hope you can help me with it.

Instabug version : 4.12.1
Crashlytics version: 2.9.1

Logcat: 
```
04-03 15:46:28.743 12782-12782/com.zadfresh.zadfresh E/CrashlyticsCore: Failed to execute task.
    java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:176)
        at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:41)
        at com.crashlytics.android.core.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:320)
        at com.crashlytics.android.core.CrashlyticsController$6.onUncaughtException(CrashlyticsController.java:300)
        at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:42)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
04-03 15:46:28.743 12782-12782/com.zadfresh.zadfresh E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zadfresh.zadfresh, PID: 12782
    java.lang.NoClassDefFoundError: com.instabug.library.analytics.AnalyticsObserver$1
        at com.instabug.library.analytics.AnalyticsObserver.<init>(AnalyticsObserver.java:29)
        at com.instabug.library.analytics.AnalyticsObserver.getInstance(AnalyticsObserver.java:41)
        at com.instabug.library.Instabug$Builder.setInvocationEvent(Instabug.java:2088)
        at com.zadtec.zadfresh.Zad.setupInstabug(Zad.java:83)
        at com.zadtec.zadfresh.Zad.onCreate(Zad.java:77)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1035)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6054)
        at android.app.ActivityThread.access$1700(ActivityThread.java:218)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1805)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:7007)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

```

**Comment by ZiadAyman** [comment]
hey @MohNage7 Can you tell on what android os version you are facing the crash?

**Comment by MohNage7** [comment]
5.1.1

**Comment by MohNage7** [comment]
i tried on 8.1.0 and 6.0.1 it works well.

**Comment by MohNage7** [comment]
thanks for ignoring our issue!  
We've rolled back instabug integration.

**Comment by ZiadAyman** [comment]
Hey @MohNage7 

Please accept my sincere apologies for the late reply here. We faced some challenges and it took us sometime to get back. This was not supposed to happen so please accept my apologies on behalf of the team.

I am checking this for you and will get back asap. Can you share with me an email to contact you on so in case we need to jump in a call or something? Or if you can talk to us directly on contactus@instabug.com that would be great as well.

Thank you so much :))

**Comment by ZiadAyman** [comment]
Hey @MohNage7 
Can you make sure that multidex is enabled?  If yes, can you have your app class extends `MultiDexApplication` ? 

Let me know if this fixed the problem :)
