### ISSUE TITLE
com.instabug.library:instabug:2+ crashes with lower Android versions - 4.4

### ISSUE THREAD

**Issue by prithsharma** [Instabug/android-sample#9]
Throws the following error on initialisation and the app crashes.

```
E/AndroidRuntime( 4090): java.lang.NoClassDefFoundError: rx.plugins.RxJavaPlugins
E/AndroidRuntime( 4090):    at rx.Observable.<clinit>(Observable.java:64)
E/AndroidRuntime( 4090):    at com.instabug.library.e.a.a(NetworkManager.java:60)
E/AndroidRuntime( 4090):    at com.instabug.library.e.a.d.a(IssueService.java:61)
E/AndroidRuntime( 4090):    at com.instabug.library.InstabugIssueUploaderService.c(InstabugIssueUploaderService.java:30)
E/AndroidRuntime( 4090):    at com.instabug.library.InstabugIssueUploaderService.b(InstabugIssueUploaderService.java:22)
E/AndroidRuntime( 4090):    at com.instabug.library.g.onHandleIntent(InstabugBackgroundService.java:32)
E/AndroidRuntime( 4090):    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/AndroidRuntime( 4090):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4090):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 4090):    at android.os.HandlerThread.run(HandlerThread.java:61)
```

Any ideas on the cause or resolutions?

**Comment by vezikon** [comment]
Do you use RxJava in your project?
