### ISSUE TITLE
IllegalStateException: Not allowed to start service Intent

### ISSUE THREAD

**Issue by Viked** [Instabug/android-sample#93]
Hello, I have received this from fabric:

Fatal Exception: rx.exceptions.OnErrorNotImplementedException: Not allowed to start service Intent { cmp=com.dartfleet.mobile/com.instabug.chat.network.InstabugMessageUploaderService }: app is in background uid UidRecord{3e0489b u0a447 CAC  bg:+1m7s92ms idle procs:1 seq(0,0,0)}
       at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
       at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
       at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
       at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
       at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
       at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
       at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
       at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
       at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
       at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
       at com.instabug.library.core.eventbus.EventBus.post(EventBus.java:24)
       at com.instabug.library.core.eventbus.coreeventbus.a.a(SDKCoreEventPublisher.java:9)
       at com.instabug.library.e.a(SessionManager.java:211)
       at com.instabug.library.e.f(SessionManager.java:90)
       at com.instabug.library.e.e(SessionManager.java:80)
       at com.instabug.library.e.a(SessionManager.java:33)
       at com.instabug.library.e$1.a(SessionManager.java:223)
       at com.instabug.library.e$1.call(SessionManager.java:218)
       at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
       at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
       at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
       at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
       at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
       at com.instabug.library.core.eventbus.EventBus.post(EventBus.java:24)
       at com.instabug.library.tracking.InstabugInternalTrackingDelegate.handleActivityStartedEvent(InstabugInternalTrackingDelegate.java:103)
       at com.instabug.library.tracking.a.onActivityStarted(InstabugActivityLifecycleListener.java:20)
       at android.app.Application.dispatchActivityStarted(Application.java:231)
       at android.app.Activity.onStart(Activity.java:1296)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:564)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
       at com.arellomobile.mvp.MvpAppCompatActivity.onStart(MvpAppCompatActivity.java:27)
       at com.dartfleet.mobile.common.activities.BaseMvpActivity.onStart(BaseMvpActivity.java:66)
       at com.dartfleet.mobile.modules.map.MapActivity.onStart(MapActivity.java:399)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
       at android.app.Activity.performStart(Activity.java:7191)
       at android.app.Activity.performRestart(Activity.java:7331)
       at android.app.ActivityThread.handleWindowVisibility(ActivityThread.java:4352)
       at android.app.ActivityThread.-wrap30(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1735)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6940)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Caused by java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.dartfleet.mobile/com.instabug.chat.network.InstabugMessageUploaderService }: app is in background uid UidRecord{3e0489b u0a447 CAC  bg:+1m7s92ms idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
       at android.app.ContextImpl.startService(ContextImpl.java:1484)
       at android.content.ContextWrapper.startService(ContextWrapper.java:663)
       at com.instabug.chat.b.d(CoreEventsHandler.java:92)
       at com.instabug.chat.b.a(CoreEventsHandler.java:61)
       at com.instabug.chat.b.a(CoreEventsHandler.java:39)
       at com.instabug.chat.a$2.a(ChatPluginWrapper.java:116)
       at com.instabug.chat.a$2.call(ChatPluginWrapper.java:113)
       at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
       at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
       at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
       at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
       at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
       at com.instabug.library.core.eventbus.EventBus.post(EventBus.java:24)
       at com.instabug.library.core.eventbus.coreeventbus.a.a(SDKCoreEventPublisher.java:9)
       at com.instabug.library.e.a(SessionManager.java:211)
       at com.instabug.library.e.f(SessionManager.java:90)
       at com.instabug.library.e.e(SessionManager.java:80)
       at com.instabug.library.e.a(SessionManager.java:33)
       at com.instabug.library.e$1.a(SessionManager.java:223)
       at com.instabug.library.e$1.call(SessionManager.java:218)
       at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
       at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
       at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
       at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
       at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
       at com.instabug.library.core.eventbus.EventBus.post(EventBus.java:24)
       at com.instabug.library.tracking.InstabugInternalTrackingDelegate.handleActivityStartedEvent(InstabugInternalTrackingDelegate.java:103)
       at com.instabug.library.tracking.a.onActivityStarted(InstabugActivityLifecycleListener.java:20)
       at android.app.Application.dispatchActivityStarted(Application.java:231)
       at android.app.Activity.onStart(Activity.java:1296)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:564)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
       at com.arellomobile.mvp.MvpAppCompatActivity.onStart(MvpAppCompatActivity.java:27)
       at com.dartfleet.mobile.common.activities.BaseMvpActivity.onStart(BaseMvpActivity.java:66)
       at com.dartfleet.mobile.modules.map.MapActivity.onStart(MapActivity.java:399)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
       at android.app.Activity.performStart(Activity.java:7191)
       at android.app.Activity.performRestart(Activity.java:7331)
       at android.app.ActivityThread.handleWindowVisibility(ActivityThread.java:4352)
       at android.app.ActivityThread.-wrap30(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1735)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6940)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Samsung Galaxy Note 8 with android 8.0
Instabug sdk 4.13.1

**Comment by Korazy** [comment]
Hey @Viked 

Thanks for pointing this out! We'll look into it and let you know what we find.

**Comment by Korazy** [comment]
@Viked can you please upgrade to 4.13.3 and let us know if it resolved the issue for you?
