### ISSUE TITLE
Crash after sending app to background while taking a screen recording

### ISSUE THREAD

**Issue by ArusyakH** [Instabug/android-sample#97]
Caused by: java.lang.NullPointerException
        at java.io.File.<init>(File.java:262)
        at com.instabug.library.internal.video.c.c(VideoFrameSnapper.java:105)
        at com.instabug.library.internal.video.InternalScreenRecordHelper.cancel(InternalScreenRecordHelper.java:85)
        at com.instabug.library.internal.video.InternalScreenRecordHelper$1.a(InternalScreenRecordHelper.java:119)
        at com.instabug.library.internal.video.InternalScreenRecordHelper$1.call(InternalScreenRecordHelper.java:115)
        at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
        at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:305) 
        at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:220) 
        at rx.subjects.PublishSubject.onNext(PublishSubject.java:73) 
        at com.instabug.library.core.eventbus.EventBus.post(EventBus.java:24) 
        at com.instabug.library.e.a(SessionManager.java:209) 
        at com.instabug.library.e.h(SessionManager.java:112) 
        at com.instabug.library.e.c(SessionManager.java:75) 
        at com.instabug.library.tracking.a.onTrimMemory(InstabugActivityLifecycleListener.java:60) 
        at android.app.Application.onTrimMemory(Application.java:136) 
        at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:5009) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119)

**Comment by Korazy** [comment]
Hey @ArusyakH 

Thanks for reporting this. Would you be able to tell me which SDK version you're currently on?
